baseurl: /jekyll_demo
url: http://www6v.github.com    
title: www6v's blog 
subtitle:  Blog for WangWei. 
author: WangWei 
simple_search: http://www.google.com.hk/search 
description: Blog for WangWei.
subscribe_rss: /atom.xml 
subscribe_email: 
email: www6v@126.com
root:/  
permalink: /blog/:year/:month/:day/:title/ 